// Generated by sprotodump. DO NOT EDIT!
using System;
using Sproto;
using System.Collections.Generic;

public class C2sProtocol : ProtocolBase {
	public static  C2sProtocol Instance = new C2sProtocol();
	private C2sProtocol() {
		Protocol.SetProtocol<call> (call.Tag);
		Protocol.SetRequest<C2sSprotoType.call.request> (call.Tag);
		Protocol.SetResponse<C2sSprotoType.call.response> (call.Tag);

		Protocol.SetProtocol<checkindaily> (checkindaily.Tag);
		Protocol.SetResponse<C2sSprotoType.checkindaily.response> (checkindaily.Tag);

		Protocol.SetProtocol<cmatch> (cmatch.Tag);
		Protocol.SetResponse<C2sSprotoType.cmatch.response> (cmatch.Tag);

		Protocol.SetProtocol<create> (create.Tag);
		Protocol.SetRequest<C2sSprotoType.create.request> (create.Tag);
		Protocol.SetResponse<C2sSprotoType.create.response> (create.Tag);

		Protocol.SetProtocol<dice> (dice.Tag);
		Protocol.SetRequest<C2sSprotoType.dice.request> (dice.Tag);
		Protocol.SetResponse<C2sSprotoType.dice.response> (dice.Tag);

		Protocol.SetProtocol<first> (first.Tag);
		Protocol.SetResponse<C2sSprotoType.first.response> (first.Tag);

		Protocol.SetProtocol<handshake> (handshake.Tag);
		Protocol.SetResponse<C2sSprotoType.handshake.response> (handshake.Tag);

		Protocol.SetProtocol<join> (join.Tag);
		Protocol.SetRequest<C2sSprotoType.join.request> (join.Tag);
		Protocol.SetResponse<C2sSprotoType.join.response> (join.Tag);

		Protocol.SetProtocol<lead> (lead.Tag);
		Protocol.SetRequest<C2sSprotoType.lead.request> (lead.Tag);
		Protocol.SetResponse<C2sSprotoType.lead.response> (lead.Tag);

		Protocol.SetProtocol<leave> (leave.Tag);
		Protocol.SetResponse<C2sSprotoType.leave.response> (leave.Tag);

		Protocol.SetProtocol<match> (match.Tag);
		Protocol.SetRequest<C2sSprotoType.match.request> (match.Tag);
		Protocol.SetResponse<C2sSprotoType.match.response> (match.Tag);

		Protocol.SetProtocol<restart> (restart.Tag);
		Protocol.SetRequest<C2sSprotoType.restart.request> (restart.Tag);
		Protocol.SetResponse<C2sSprotoType.restart.response> (restart.Tag);

		Protocol.SetProtocol<shuffle> (shuffle.Tag);
		Protocol.SetRequest<C2sSprotoType.shuffle.request> (shuffle.Tag);
		Protocol.SetResponse<C2sSprotoType.shuffle.response> (shuffle.Tag);

		Protocol.SetProtocol<step> (step.Tag);
		Protocol.SetRequest<C2sSprotoType.step.request> (step.Tag);
		Protocol.SetResponse<C2sSprotoType.step.response> (step.Tag);

	}

	public class call {
		public const int Tag = 7;
	}

	public class checkindaily {
		public const int Tag = 21;
	}

	public class cmatch {
		public const int Tag = 3;
	}

	public class create {
		public const int Tag = 4;
	}

	public class dice {
		public const int Tag = 9;
	}

	public class first {
		public const int Tag = 20;
	}

	public class handshake {
		public const int Tag = 1;
	}

	public class join {
		public const int Tag = 5;
	}

	public class lead {
		public const int Tag = 10;
	}

	public class leave {
		public const int Tag = 6;
	}

	public class match {
		public const int Tag = 2;
	}

	public class restart {
		public const int Tag = 12;
	}

	public class shuffle {
		public const int Tag = 8;
	}

	public class step {
		public const int Tag = 11;
	}

}