// Generated by sprotodump. DO NOT EDIT!
using System;
using Sproto;
using System.Collections.Generic;

public class C2sProtocol : ProtocolBase {
	public static  C2sProtocol Instance = new C2sProtocol();
	private C2sProtocol() {
		Protocol.SetProtocol<avatar> (avatar.Tag);
		Protocol.SetResponse<C2sSprotoType.avatar.response> (avatar.Tag);

		Protocol.SetProtocol<call> (call.Tag);
		Protocol.SetRequest<C2sSprotoType.call.request> (call.Tag);
		Protocol.SetResponse<C2sSprotoType.call.response> (call.Tag);

		Protocol.SetProtocol<checkindaily> (checkindaily.Tag);
		Protocol.SetResponse<C2sSprotoType.checkindaily.response> (checkindaily.Tag);

		Protocol.SetProtocol<cmatch> (cmatch.Tag);
		Protocol.SetResponse<C2sSprotoType.cmatch.response> (cmatch.Tag);

		Protocol.SetProtocol<create> (create.Tag);
		Protocol.SetRequest<C2sSprotoType.create.request> (create.Tag);
		Protocol.SetResponse<C2sSprotoType.create.response> (create.Tag);

		Protocol.SetProtocol<dice> (dice.Tag);
		Protocol.SetRequest<C2sSprotoType.dice.request> (dice.Tag);
		Protocol.SetResponse<C2sSprotoType.dice.response> (dice.Tag);

		Protocol.SetProtocol<fetchsysmail> (fetchsysmail.Tag);
		Protocol.SetRequest<C2sSprotoType.fetchsysmail.request> (fetchsysmail.Tag);
		Protocol.SetResponse<C2sSprotoType.fetchsysmail.response> (fetchsysmail.Tag);

		Protocol.SetProtocol<first> (first.Tag);
		Protocol.SetResponse<C2sSprotoType.first.response> (first.Tag);

		Protocol.SetProtocol<handshake> (handshake.Tag);
		Protocol.SetResponse<C2sSprotoType.handshake.response> (handshake.Tag);

		Protocol.SetProtocol<join> (join.Tag);
		Protocol.SetRequest<C2sSprotoType.join.request> (join.Tag);
		Protocol.SetResponse<C2sSprotoType.join.response> (join.Tag);

		Protocol.SetProtocol<lead> (lead.Tag);
		Protocol.SetRequest<C2sSprotoType.lead.request> (lead.Tag);
		Protocol.SetResponse<C2sSprotoType.lead.response> (lead.Tag);

		Protocol.SetProtocol<leave> (leave.Tag);
		Protocol.SetRequest<C2sSprotoType.leave.request> (leave.Tag);
		Protocol.SetResponse<C2sSprotoType.leave.response> (leave.Tag);

		Protocol.SetProtocol<logout> (logout.Tag);
		Protocol.SetResponse<C2sSprotoType.logout.response> (logout.Tag);

		Protocol.SetProtocol<match> (match.Tag);
		Protocol.SetRequest<C2sSprotoType.match.request> (match.Tag);
		Protocol.SetResponse<C2sSprotoType.match.response> (match.Tag);

		Protocol.SetProtocol<rchat> (rchat.Tag);
		Protocol.SetRequest<C2sSprotoType.rchat.request> (rchat.Tag);
		Protocol.SetResponse<C2sSprotoType.rchat.response> (rchat.Tag);

		Protocol.SetProtocol<record> (record.Tag);
		Protocol.SetRequest<C2sSprotoType.record.request> (record.Tag);
		Protocol.SetResponse<C2sSprotoType.record.response> (record.Tag);

		Protocol.SetProtocol<records> (records.Tag);
		Protocol.SetResponse<C2sSprotoType.records.response> (records.Tag);

		Protocol.SetProtocol<restart> (restart.Tag);
		Protocol.SetRequest<C2sSprotoType.restart.request> (restart.Tag);
		Protocol.SetResponse<C2sSprotoType.restart.response> (restart.Tag);

		Protocol.SetProtocol<shuffle> (shuffle.Tag);
		Protocol.SetRequest<C2sSprotoType.shuffle.request> (shuffle.Tag);
		Protocol.SetResponse<C2sSprotoType.shuffle.response> (shuffle.Tag);

		Protocol.SetProtocol<step> (step.Tag);
		Protocol.SetRequest<C2sSprotoType.step.request> (step.Tag);
		Protocol.SetResponse<C2sSprotoType.step.response> (step.Tag);

		Protocol.SetProtocol<syncsysmail> (syncsysmail.Tag);
		Protocol.SetRequest<C2sSprotoType.syncsysmail.request> (syncsysmail.Tag);
		Protocol.SetResponse<C2sSprotoType.syncsysmail.response> (syncsysmail.Tag);

		Protocol.SetProtocol<test> (test.Tag);
		Protocol.SetRequest<C2sSprotoType.test.request> (test.Tag);
		Protocol.SetResponse<C2sSprotoType.test.response> (test.Tag);

		Protocol.SetProtocol<toast1> (toast1.Tag);
		Protocol.SetResponse<C2sSprotoType.toast1.response> (toast1.Tag);

		Protocol.SetProtocol<toast2> (toast2.Tag);
		Protocol.SetResponse<C2sSprotoType.toast2.response> (toast2.Tag);

		Protocol.SetProtocol<viewedsysmail> (viewedsysmail.Tag);
		Protocol.SetRequest<C2sSprotoType.viewedsysmail.request> (viewedsysmail.Tag);
		Protocol.SetResponse<C2sSprotoType.viewedsysmail.response> (viewedsysmail.Tag);

		Protocol.SetProtocol<xuanpao> (xuanpao.Tag);
		Protocol.SetRequest<C2sSprotoType.xuanpao.request> (xuanpao.Tag);
		Protocol.SetResponse<C2sSprotoType.xuanpao.response> (xuanpao.Tag);

		Protocol.SetProtocol<xuanque> (xuanque.Tag);
		Protocol.SetRequest<C2sSprotoType.xuanque.request> (xuanque.Tag);
		Protocol.SetResponse<C2sSprotoType.xuanque.response> (xuanque.Tag);

	}

	public class avatar {
		public const int Tag = 19;
	}

	public class call {
		public const int Tag = 501;
	}

	public class checkindaily {
		public const int Tag = 8;
	}

	public class cmatch {
		public const int Tag = 3;
	}

	public class create {
		public const int Tag = 4;
	}

	public class dice {
		public const int Tag = 503;
	}

	public class fetchsysmail {
		public const int Tag = 12;
	}

	public class first {
		public const int Tag = 7;
	}

	public class handshake {
		public const int Tag = 1;
	}

	public class join {
		public const int Tag = 5;
	}

	public class lead {
		public const int Tag = 504;
	}

	public class leave {
		public const int Tag = 6;
	}

	public class logout {
		public const int Tag = 17;
	}

	public class match {
		public const int Tag = 2;
	}

	public class rchat {
		public const int Tag = 507;
	}

	public class record {
		public const int Tag = 16;
	}

	public class records {
		public const int Tag = 15;
	}

	public class restart {
		public const int Tag = 506;
	}

	public class shuffle {
		public const int Tag = 502;
	}

	public class step {
		public const int Tag = 505;
	}

	public class syncsysmail {
		public const int Tag = 13;
	}

	public class test {
		public const int Tag = 18;
	}

	public class toast1 {
		public const int Tag = 9;
	}

	public class toast2 {
		public const int Tag = 10;
	}

	public class viewedsysmail {
		public const int Tag = 14;
	}

	public class xuanpao {
		public const int Tag = 508;
	}

	public class xuanque {
		public const int Tag = 509;
	}

}